---
# Source: snyky/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: snyky
  labels:
    app.kubernetes.io/name: snyky
    helm.sh/chart: snyky-0.1.0
    app.kubernetes.io/instance: snyky
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: snyky
    app.kubernetes.io/instance: snyky
---
# Source: snyky/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snyky
  labels:
    app.kubernetes.io/name: snyky
    helm.sh/chart: snyky-0.1.0
    app.kubernetes.io/instance: snyky
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: snyky
      app.kubernetes.io/instance: snyky
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snyky
        app.kubernetes.io/instance: snyky
    spec:
      containers:
        - name: snyky
          image: "garethr/snyky:slim"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
